default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: fake_news_api_development
  username: postgres
test:
  <<: *default
  database: fake_news_api_test
  username: postgres
production:
  <<: *default
  database: fake_news_api_production
  username: fake_news_api
  password: <%= ENV['FAKE_NEWS_API_DATABASE_PASSWORD'] %>
